### ISSUE TITLE
Add R script for data analysis and graphics

### ISSUE THREAD

**Issue by alephmembeth** [alephmembeth/causality-revolver#1]

**Comment by alephmembeth** [comment]
If I'm not mistaken, we have to add `Revolver.Data.Study.797` and `Revolver.Data.Study.798` for the script to work.

**Comment by JKRhb** [comment]
> If I'm not mistaken, we have to add `Revolver.Data.Study.797` and `Revolver.Data.Study.798` for the script to work.

Good point, let's reopen this issue as a reminder :)

**Comment by JKRhb** [comment]
... or let's use #6 instead? ;)

**Comment by JKRhb** [comment]
Superseded by #6.
